project:
  type: website

website:
  page-navigation: true
  title: "Introduction to R and Basic Data Analysis"
  site-url: "https://bookdown.org/federicagazzelloni/ACTEX_october2024/" 
  repo-url: https://github.com/Fgazzelloni/ACTEX_october2024
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By AFDP 2024 - ACTEX Learning"  
  
  sidebar:
    logo: "images/actex_logo.png"
    style: "docked"
    search: true
    collapse-level: 1
    toc: true
    contents:
      - text: "1. Welcome"
        href: index.qmd
      - text: "2. Introduction to R"
        href: 01_introduction_to_r.qmd  
      - text: "3. Basic Examples"
        href: 02_practice_with_r.qmd
      - section: "4. Predictive Modeling"
        contents:
          - text: "4.1 Introduction"
            href: 03_introduction_to_pm.qmd
          - text: "4.2 Practice Predictive Modeling"
            href: 04_practice_pm.qmd
      - text: "Final Project"
        href: 05_final_project.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

