---
title: "Introduction to R and Basic Data Analysis for Actuarial Science"
description: "Actuarial Faculty Development Program 2025 - ACTEX Learning"
date: "2025/09/02"
format:
  html:
    toc: true
---

**This course is designed to equip participants with a structured approach to learn essential R skills required for actuarial exams**

## Instructors

::::: columns
::: column
-   **Federica Gazzelloni, IIA**
    -   Email: [fede.gazzelloni\@gmail.com](mailto:fede.gazzelloni@gmail.com){.email}
    -   Website: [federicagazzelloni.com](https://federicagazzelloni.com)
    -   LinkedIn: [federicagazzelloni](https://www.linkedin.com/in/federicagazzelloni/)
:::

::: column
-   **Farid Flici, PHD**
    -   Email: [farid.flici\@gmail.com](mailto:farid.flici@gmail.com){.email}
    -   Website: [farid-flici.github.io](https://farid-flici.github.io/)
    -   LinkedIn: [faridflici](https://www.linkedin.com/in/farid-flici-659a7625/)
:::
:::::

## Course Description

This course equips participants with practical skills for using R in actuarial science. It focuses on the technical competencies needed for actuarial exams that incorporate data analysis and modeling, such as Predictive Analytics and Statistics for Risk Modeling (SRM). The session emphasizes hands-on, exam-relevant techniques that can be integrated into academic curricula or review programs.

Participants will learn efficient methods for importing and manipulating data, applying actuarial functions, and implementing statistical models frequently tested in actuarial contexts. Topics include generalized linear models (GLMs) for claim frequency and severity, predictive modeling techniques such as clustering and regularization, as well as visualization and reporting strategies to enhance clarity and reproducibility.

The course includes practical exercises and adaptable templates, ensuring students are well-prepared for R-based actuarial assessments.

Designed for participants with little or no programming experience, this course offers a structured and targeted introduction to R, focusing on the topics most relevant for actuarial applications.

### Learning Objectives

By the end of this course, participants will be able to:

-   Understand the essential R topics for actuarial exams.
-   Learn how to structure a short R module for exam preparation.
-   Gain ready-to-use teaching materials (cheat sheet, Quarto template, exercises with solutions).
-   Explore strategies to improve coding effectively under exam conditions.

### Prerequisites

This program is designed for both aspiring and experienced actuaries who want to deepen their expertise in data analysis and programming:

-   Basic Knowledge of Probability and Statistics – familiarity with descriptive statistics, probability distributions, and regression concepts.
-   Actuarial Exam Foundations – prior exposure to material from preliminary exams such as P (Probability) and FM (Financial Mathematics).
-   Basic Computing Skills – ability to navigate a computer environment and install software; no prior programming experience required.

### Course Outline

This two-hour R-crash course will cover the basics of R programming, with a focus on practical applications relevant to actuarial exams.

-   [Introduction to R](/01_introduction_to_r.html)
-   [Data types and structures](/02_data_types_and_structures.html)
-   Example 1: [Data manipulation and visualization](/03_data_manipulation_and_visualization.html)
-   Example 2: [Predictive modeling](/04_predictive_modeling.html)
-   Example 3: [Clustering](/05_clustering.html)

### Course Materials

- This Booklet: <https://bookdown.org/federicagazzelloni/ACTEX_2025/>
- Slides and other files: <https://www.actuarialuniversity.com/seminar/View/15335>
- Github repository: <https://github.com/Fgazzelloni/ACTEX_2025>


## About the Providers

[ACTEX Learning](https://www.actexlearning.com/) is a long-established leader in actuarial exam preparation, best known for its high-quality study manuals and adaptive learning tools. Their resources are branded with confidence: **"Empowering Actuarial Students. Proven Results."** Their materials are designed for flexibility, allowing learners to study at their own pace and engage with interactive elements such as video lectures and GOAL practice tools—**"Guided Online Actuarial Learning"**—which offers exam-style questions across varied difficulty levels. Many professors also endorse ACTEX materials, relying on their structured content and pass-focused approach.

[Actuarial University](https://www.actuarialuniversity.com/), powered by **ACTEX** and [Mad River Books](https://www.actexmadriver.com/), serves as a centralized learning platform tailored specifically for students and instructors. Through a unified login experience, users gain access to study materials, e-books, GOAL practice sets, and exam dashboards customized for numerous actuarial exams. The platform is designed for ease of use—offering topic indexing, planner tools, and instructor-friendly features that support seamless integration into actuarial courses.
